name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/springbootapp:${{ github.run_number }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/springbootapp:${{ github.run_number }}
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/springbootapp:${{ github.run_number }} ${{ secrets.DOCKER_HUB_USERNAME }}/springbootapp:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/springbootapp:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl config set-context --current --namespace=orbit-bank-apps
          kubectl apply -f orbit-bank.yaml

